### PR TITLE
Fix range inputs

### PR DESCRIPTION
**Pull request by MarvinKlein1508**
Range inputs doesn't work when you want to use them with `float`, `double` or `decimal` when `CultureInfo` uses a `,` as seperator for floating points.

Otherwise the component will behave buggy and renders invalid HTML.

This patch fixes this behaviour by always using `CultureInfo.InvariantCulture` to always work in all localizations.

### CODE REVIEW

**Comment by gvreddy04** [comment]
@MarvinKlein1508 I'm reviewing this PR. Could you help me reproduce this issue? If you wouldn't mind, could you share a screen recording of the issue?

**Comment by MarvinKlein1508** [comment]
@gvreddy04 the decimal demo I've added is showcasing this issue. All your need is a browser with a locale which uses `,` as decimal separator

**Comment by MarvinKlein1508** [comment]
RANGE

See:
html-range

Fixing only the representation in the DOM doesn't fix the issue because the same problem occurs from the sent Javascript value. That's why the convert functions need to use `CultureInfo.InvarientCulture` as well.

**Comment by gvreddy04** [comment]
> Fixing only the representation in the DOM doesn't fix the issue because the same problem occurs from the sent Javascript value. That's why the convert functions need to use `CultureInfo.InvarientCulture` as well.

@MarvinKlein1508  Thank you for your quick reply on this. I'll test and complete this PR.

**Comment by gvreddy04** [comment]
@MarvinKlein1508 I changed the browser language to French to reproduce the issue, but I was not able to reproduce it. Please let me know if I'm missing anything. Additionally, please share the steps you followed to change the browser language.

image

image

**Comment by MarvinKlein1508** [comment]
If I remember correctly then Google Chrome automatically fixes the behaviour. We had this issue for `InputNumber` compoennts in our app in the past as well.

Try Firefox with German locale.

**Comment by MarvinKlein1508** [comment]
It's also broken on Safari on with locale which uses `,` as separator

**Comment by gvreddy04** [comment]
@MarvinKlein1508 I was able to replicate this issue by using Opera with German.

**Review by gvreddy04 — APPROVED** [review]
LGTM

**Pull request merged**
