### PR TITLE
Correct the typo in Toggle/Toogle

### LINKED ISSUE #583: Typo in Toggle
There is a typo in some of the toggle button names. In some places, the word `Toogle` [sic] is used instead of `Toggle`.

~~~diff
diff --git a/BlazorBootstrap.Demo.RCL/Pages/Sidebar/Sidebar_Demo_05_Toggle_Sidebar_to_Show_Icons_Only.razor b/BlazorBootstrap.Demo.RCL/Pages/Sidebar/Sidebar_Demo_05_Toggle_Sidebar_to_Show_Icons_Only.razor
index a05af1f4..cc0a5888 100644
--- a/BlazorBootstrap.Demo.RCL/Pages/Sidebar/Sidebar_Demo_05_Toggle_Sidebar_to_Show_Icons_Only.razor
+++ b/BlazorBootstrap.Demo.RCL/Pages/Sidebar/Sidebar_Demo_05_Toggle_Sidebar_to_Show_Icons_Only.razor
@@ -7,7 +7,7 @@
 
     <main>
         <div class="bb-top-row px-4 d-flex justify-content-between">
-            <Icon Name="IconName.List" role="button" @onclick="ToogleSidebar" />
+            <Icon Name="IconName.List" role="button" @onclick="ToggleSidebar" />
             <a href="https://docs.microsoft.com/aspnet/" target="_blank">About</a>
         </div>
 
@@ -54,5 +54,5 @@
         return navItems;
     }
 
-    private void ToogleSidebar() => sidebar.ToggleSidebar();
+    private void ToggleSidebar() => sidebar.ToggleSidebar();
 }
diff --git a/BlazorBootstrap.Demo.RCL/Pages/Sidebar/Sidebar_Demo_06_Show_Badge.razor b/BlazorBootstrap.Demo.RCL/Pages/Sidebar/Sidebar_Demo_06_Show_Badge.razor
index d1c3f2e0..e46dda89 100644
--- a/BlazorBootstrap.Demo.RCL/Pages/Sidebar/Sidebar_Demo_06_Show_Badge.razor
+++ b/BlazorBootstrap.Demo.RCL/Pages/Sidebar/Sidebar_Demo_06_Show_Badge.razor
@@ -8,7 +8,7 @@
 
     <main>
         <div class="bb-top-row px-4 d-flex justify-content-between">
-            <Icon Name="IconName.List" role="button" @onclick="ToogleSidebar" />
+            <Icon Name="IconName.List" role="button" @onclick="ToggleSidebar" />
             <a href="https://docs.microsoft.com/aspnet/" target="_blank">About</a>
         </div>
 
@@ -55,5 +55,5 @@
         return navItems;
     }
 
-    private void ToogleSidebar() => sidebar.ToggleSidebar();
+    private void ToggleSidebar() => sidebar.ToggleSidebar();
 }
diff --git a/BlazorBootstrap.Demo.RCL/Pages/Sidebar/Sidebar_Demo_07_Custom_Brand_Icon.razor b/BlazorBootstrap.Demo.RCL/Pages/Sidebar/Sidebar_Demo_07_Custom_Brand_Icon.razor
index 6239414f..2773886d 100644
--- a/BlazorBootstrap.Demo.RCL/Pages/Sidebar/Sidebar_Demo_07_Custom_Brand_Icon.razor
+++ b/BlazorBootstrap.Demo.RCL/Pages/Sidebar/Sidebar_Demo_07_Custom_Brand_Icon.razor
@@ -8,7 +8,7 @@
 
     <main>
         <div class="bb-top-row px-4 d-flex justify-content-between">
-            <Icon Name="IconName.List" role="button" @onclick="ToogleSidebar" />
+            <Icon Name="IconName.List" role="button" @onclick="ToggleSidebar" />
             <a href="https://docs.microsoft.com/aspnet/" target="_blank">About</a>
         </div>
 
@@ -55,5 +55,5 @@
         return navItems;
     }
 
-    private void ToogleSidebar() => sidebar.ToggleSidebar();
+    private void ToggleSidebar() => sidebar.ToggleSidebar();
 }
diff --git a/BlazorBootstrap.Demo.RCL/Pages/Sidebar/Sidebar_Demo_08_Show_Image_as_Brand_Logo.razor b/BlazorBootstrap.Demo.RCL/Pages/Sidebar/Sidebar_Demo_08_Show_Image_as_Brand_Logo.razor
index 9bb62a7a..f671688e 100644
--- a/BlazorBootstrap.Demo.RCL/Pages/Sidebar/Sidebar_Demo_08_Show_Image_as_Brand_Logo.razor
+++ b/BlazorBootstrap.Demo.RCL/Pages/Sidebar/Sidebar_Demo_08_Show_Image_as_Brand_Logo.razor
@@ -8,7 +8,7 @@
 
     <main>
         <div class="bb-top-row px-4 d-flex justify-content-between">
-            <Icon Name="IconName.List" role="button" @onclick="ToogleSidebar" />
+            <Icon Name="IconName.List" role="button" @onclick="ToggleSidebar" />
             <a href="https://docs.microsoft.com/aspnet/" target="_blank">About</a>
         </div>
 
@@ -55,5 +55,5 @@
         return navItems;
     }
 
-    private void ToogleSidebar() => sidebar.ToggleSidebar();
+    private void ToggleSidebar() => sidebar.ToggleSidebar();
 }
diff --git a/blazorbootstrap/Components/Button/Button.razor.cs b/blazorbootstrap/Components/Button/Button.razor.cs
index 1de31909..46d4df41 100644
--- a/blazorbootstrap/Components/Button/Button.razor.cs
+++ b/blazorbootstrap/Components/Button/Button.razor.cs
@@ -482,6 +482,6 @@ public partial class Button : BlazorBootstrapComponentBase
 
     // TODO: Review
     // - Disable text wrapping: https://getbootstrap.com/docs/5.1/components/buttons/#disable-text-wrapping
-    // - Toogle states: https://getbootstrap.com/docs/5.1/components/buttons/#toggle-states
+    // - Toggle states: https://getbootstrap.com/docs/5.1/components/buttons/#toggle-states
     // - IDispose
 }
diff --git a/docs/docs/05-components/buttons.md b/docs/docs/05-components/buttons.md
index c5f8faaf..9ffccdba 100644
--- a/docs/docs/05-components/buttons.md
+++ b/docs/docs/05-components/buttons.md
@@ -213,11 +213,11 @@ Create responsive stacks of full-width, "block buttons" like those in Bootstrap
 
 [See block buttons demo here.](https://demos.blazorbootstrap.com/buttons#block-buttons)
 
-### Toogle States
+### Toggle States
 
 If you''re pre-toggling a button, you must manually add the `Active="true"` parameter.
 
-<img src="https://i.imgur.com/JH9SZxQ.jpg" alt="Blazor Bootstrap: Button Component - Button Toogle States" />
+<img src="https://i.imgur.com/JH9SZxQ.jpg" alt="Blazor Bootstrap: Button Component - Button Toggle States" />
 
 ```cshtml showLineNumbers
 <p>
@@ -227,7 +227,7 @@ If you''re pre-toggling a button, you must manually add the `Active="true"` para
 </p>
 ```
 
-[See button toogle states demo here.](https://demos.blazorbootstrap.com/buttons#toggle-states)
+[See button toggle states demo here.](https://demos.blazorbootstrap.com/buttons#toggle-states)
 
 ### Loading spinner
 
diff --git a/docs/docs/05-components/sidebar.md b/docs/docs/05-components/sidebar.md
index aecedbab..6e759aa6 100644
--- a/docs/docs/05-components/sidebar.md
+++ b/docs/docs/05-components/sidebar.md
@@ -278,7 +278,7 @@ Call `ToggleSidebar()` method to toggle the Sidebar to show the icons only.
 
     <main>
         <div class="bb-top-row px-4 d-flex justify-content-between">
-            <Icon Name="IconName.List" role="button" @onclick="ToogleSidebar" />
+            <Icon Name="IconName.List" role="button" @onclick="ToggleSidebar" />
             <a href="https://docs.microsoft.com/aspnet/" target="_blank">About</a>
         </div>
 
@@ -325,7 +325,7 @@ Call `ToggleSidebar()` method to toggle the Sidebar to show the icons only.
         return navItems;
     }
 
-    private void ToogleSidebar() => sidebar.ToggleSidebar();
+    private void ToggleSidebar() => sidebar.ToggleSidebar();
 }
 ```
 
@@ -348,7 +348,7 @@ A badge is useful when displaying the application version, environment, or other
 
     <main>
         <div class="bb-top-row px-4 d-flex justify-content-between">
-            <Icon Name="IconName.List" role="button" @onclick="ToogleSidebar" />
+            <Icon Name="IconName.List" role="button" @onclick="ToggleSidebar" />
             <a href="https://docs.microsoft.com/aspnet/" target="_blank">About</a>
         </div>
 
@@ -395,7 +395,7 @@ A badge is useful when displaying the application version, environment, or other
         return navItems;
     }
 
-    private void ToogleSidebar() => sidebar.ToggleSidebar();
+    private void ToggleSidebar() => sidebar.ToggleSidebar();
 }
 \`\`\`
 
@@ -418,7 +418,7 @@ Use the `CustomIconName` parameter to set the custom logo icon using font awesom
 
     <main>
         <div class="bb-top-row px-4 d-flex justify-content-between">
-            <Icon Name="IconName.List" role="button" @onclick="ToogleSidebar" />
+            <Icon Name="IconName.List" role="button" @onclick="ToggleSidebar" />
             <a href="https://docs.microsoft.com/aspnet/" target="_blank">About</a>
         </div>
 
@@ -465,7 +465,7 @@ Use the `CustomIconName` parameter to set the custom logo icon using font awesom
         return navItems;
     }
 
-    private void ToogleSidebar() => sidebar.ToggleSidebar();
+    private void ToggleSidebar() => sidebar.ToggleSidebar();
 }
 ```
 
@@ -488,7 +488,7 @@ Use the `ImageSrc` parameter to set the brand logo.
 
     <main>
         <div class="bb-top-row px-4 d-flex justify-content-between">
-            <Icon Name="IconName.List" role="button" @onclick="ToogleSidebar" />
+            <Icon Name="IconName.List" role="button" @onclick="ToggleSidebar" />
             <a href="https://docs.microsoft.com/aspnet/" target="_blank">About</a>
         </div>
 
@@ -535,7 +535,7 @@ Use the `ImageSrc` parameter to set the brand logo.
         return navItems;
     }
 
-    private void ToogleSidebar() => sidebar.ToggleSidebar();
+    private void ToggleSidebar() => sidebar.ToggleSidebar();
 }
 ```
~~~

### PR DESCRIPTION
**Pull request by mavaddat**
Corrects #583 typo of `Toogle` in some places where the correct spelling `Toggle` was intended.

### CODE REVIEW

**Comment by gvreddy04** [comment]
@mavaddat Thank you for the PR.

**Comment by gvreddy04** [comment]
@mavaddat PR changes look good to me. Please resolve the conflicts.

**Comment by mavaddat** [comment]
> Please resolve the conflicts.

Done.

**Review by gvreddy04 — APPROVED** [review]
LGTM.

**Pull request merged**
