### PR TITLE
Allow to return objects from tab buttons

### PR DESCRIPTION
**Pull request by MarvinKlein1508**
This PR adds a new feature to tabs which allows the user to return a custom object when the nav button of a tab has been clicked.

This is for use-cases where tabs are being used to render content for a list of objects. It's important to know which object is currently selected to adjust some logic on your blazor page.

I've added a short demo as well.

In my case I need this functionality to show a list of positions. Depending on the selected position I display additional information outside of the `Tabs` control.

Implementation might not be perfect but it works fine in my case. Feel free to suggest changes.

### CODE REVIEW

**Comment by MarvinKlein1508** [comment]
@gvreddy04 There is one thing left todo here. I've noticed that the property IsShown does not trigger a a tab activation when the property is changed from outside.

**Comment by MarvinKlein1508** [comment]
To reproduce:

```csharp
<Tabs>
    @foreach (var customer in customers)
    {
        <Tab IsActive="selectedCustomer == customer" OnTabClicked="async () => await OnTabClickedAsync(customer)" Title="@customer.CustomerName">
            <Content>
                <div class="mt-3">
                    This is the placeholder content for the <b>@customer.CustomerName</b> tab.
                </div>
            </Content>
        </Tab>
    }
</Tabs>

@if (selectedCustomer is not null)
{
    <div class="mt-3">Selected customer: <b>@selectedCustomer.CustomerName</b></div>
}

<Button Color="ButtonColor.Success">Add customer</Button>

@code {
    private List<Customer> customers = new()
                                       {
                                           new Customer(1, "Marvin Klein"),
                                           new Customer(2, "Vikram Reddy"),
                                           new Customer(3, "Bandita PA"),
                                           new Customer(4, "Daina JJ")
                                       };



    private Customer? selectedCustomer;

    protected override void OnInitialized()
    {
        selectedCustomer = customers.First();
    }

    private Task AddCustomerAsync()
    {
        var customer = new Customer(5, "Hello World");

        customers.Add(customer);

        selectedCustomer = customer;

        return Task.CompletedTask;
    }

    private Task OnTabClickedAsync(Customer customer)
    {
        selectedCustomer = customer;
        return Task.CompletedTask;
    }
}
```

Notice how active tab does not change when `selectedCustomer` changes outside of the tab control. This also applies for all other tabs.

**Comment by MarvinKlein1508** [comment]
@gvreddy04 did you consider my last comment here?

**Comment by gvreddy04** [comment]
@MarvinKlein1508 I missed the scenario. I think a few people asked for dynamic tabs. I'll check.

**Comment by gvreddy04** [comment]
Dynamically adding tabs #480

**Comment by gvreddy04** [comment]
@MarvinKlein1508  Now dynamic tabs support added.

Demo code: https://github.com/vikramlearning/blazorbootstrap/blob/master/BlazorBootstrap.Demo.RCL/Pages/Tabs/Tabs_Demo_13_Dynamic_Tabs.razor

image

**Comment by MarvinKlein1508** [comment]
@gvreddy04 that's still not what I mentioned above. 

I have use-cases where I set `selectedCustomer` for example from outside. 

For example:

```csharp
<Button Color="ButtonColor.Info" Class="mt-3" @onclick="Select2ndCustomer">Select 2nd customer</Button>

@code {
private void Select2ndCustomer() {
selectedCustomer = customers[1];
}
}
```

What I expect now is tab for customer `Vikran Reddy` to be shown.

In my use-case this is triggered when running validation for an object within the list. If the validation has failed I want the tab to open automatically so the user can see the error messages on a glance.

**Comment by MarvinKlein1508** [comment]
See this gif for an example:
tabs

**Comment by MarvinKlein1508** [comment]
BTW. is there any reason for the control to rely on JavaScript in the first place? Wouldn't it be easier to implement it with vanilla HTML and C#?

What I did in previous projects was someting like this:
```html
<div class="row">
    <div class="col-md-2 mb-3">
        <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
            @foreach (var pos in Input.Positions)
            {
                <button type="button" role="tab" @onclick="() => SelectedPosition = pos" class="@GetTabNavLinkClass(SelectedPosition == pos)" id="pos-tab-@pos.GetHashCode()" data-bs-toggle="pill">(@pos.Id) @pos.Name</button>
            }
        </div>
    </div>
    <div class="col-md-10">
        <div class="tab-content">
            @foreach (var pos in Input.Positions)
            {
                int posHash = pos.GetHashCode();
                <div class="@GetTabClass(SelectedPosition == pos)" id="pos-@posHash" role="tabpanel" aria-labelledby="pos-tab-@posHash">

                    <p>Content for tab</p>

                </div>
            }

        </div>
    </div>
</div>
```

```csharp
public string GetTabNavLinkClass(bool active) => active ? "nav-link active" : "nav-link";
public string GetTabClass(bool active) => active ? "tab-pane fade active show" : "tab-pane fade";
```

**Comment by MarvinKlein1508** [comment]
ping @gvreddy04

**Comment by gvreddy04** [comment]
> See this gif for an example: tabs [ tabs ](https://private-user-images.githubusercontent.com/32510006/301275043-cbd7baf6-4122-450e-9240-efeea772892f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MTIwOTMsIm5iZiI6MTcwNjgxMTc5MywicGF0aCI6Ii8zMjUxMDAwNi8zMDEyNzUwNDMtY2JkN2JhZjYtNDEyMi00NTBlLTkyNDAtZWZlZWE3NzI4OTJmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDE4MjMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMzVjNTZlZWJjZWYzNzliZmIwNjI4NGZiNzU1ZTMwYTNmYzJhYTliNjFhOTU3ZDVmODIyZWYxNWY5MDViODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3YeDt6nm2rZnr6UbY1BRFqmjZ2uSbdQYALWkPfdAoeM) [ ](https://private-user-images.githubusercontent.com/32510006/301275043-cbd7baf6-4122-450e-9240-efeea772892f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MTIwOTMsIm5iZiI6MTcwNjgxMTc5MywicGF0aCI6Ii8zMjUxMDAwNi8zMDEyNzUwNDMtY2JkN2JhZjYtNDEyMi00NTBlLTkyNDAtZWZlZWE3NzI4OTJmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDE4MjMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMzVjNTZlZWJjZWYzNzliZmIwNjI4NGZiNzU1ZTMwYTNmYzJhYTliNjFhOTU3ZDVmODIyZWYxNWY5MDViODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3YeDt6nm2rZnr6UbY1BRFqmjZ2uSbdQYALWkPfdAoeM)

I understand the scenario. The IsActive property is currently used in the OnInitialized stage, which is why it's not working as expected. For now, please use @ref to reference the tabs and then call the appropriate methods. I'll address this issue in version 1.11.0. However, the caveat is that we cannot use both IsActive and the methods to activate any of the tabs simultaneously.

**Comment by MarvinKlein1508** [comment]
@gvreddy04 I don't think this is a problem. I think you are either using the activation via tabs or the attribute itself. The attribute might be used more frequently for dynamic tabs though.

**Pull request merged**
