### PR TITLE
Add Accordion show/hide all methods

### PR DESCRIPTION
**Pull request by jlkeiper**
We track the accordion size manually and iterate over it to show/hide all accordion items in our project. This will save us some code since the accordion already owns the item list.

### CODE REVIEW

**Comment by gvreddy04** [comment]
@jlkeiper Thank you for the PR. Could you please create a demo to cover this scenario?

Link: https://github.com/vikramlearning/blazorbootstrap/tree/master/BlazorBootstrap.Demo.RCL/Pages/Accordion

**Comment by jlkeiper** [comment]
> @jlkeiper Thank you for the PR. Could you please create a demo to cover this scenario?
> 
> Link: https://github.com/vikramlearning/blazorbootstrap/tree/master/BlazorBootstrap.Demo.RCL/Pages/Accordion

Will do!

**Comment by jlkeiper** [comment]
@gvreddy04 I added docs for the previously added Hide* methods as well. Let me know if you want different wording, I am happy to update it to suit your styles.

**Comment by jlkeiper** [comment]
image

image

**Pull request merged**
