### PR TITLE
Add more levels of navigation to sidebar

### PR DESCRIPTION
**Pull request by MarvinKlein1508**
This PR adds support for multi-level drop downs in infite amounts. 

The docs needs to be updated for this. I've tested it down to level 5. Most common use-case would be 3 levels I guess.

We achieve this by running recurive building of sub-menus.

Not sure if it breaks anything which I have not on my radar but demo app works fine for me. Feel free to test the PR with all your needs.

### CODE REVIEW

**Comment by gvreddy04** [comment]
@MarvinKlein1508 Thanks for the PR. Can you add one or two examples?

**Comment by MarvinKlein1508** [comment]
@gvreddy04 sure. I'm not familiar with your demo project structure though. The way to use this is bascially the same as for the two level navigation.

**Comment by MarvinKlein1508** [comment]
For example:
```csharp
yield return new NavItem
{
    Id = "nav-test",
    IconName = IconName.Gear,
    Text = "Test Level 1",
    IconColor = IconColor.Success,
    Match = NavLinkMatch.All
};

yield return new NavItem
{
    Id = "nav-test2",
    IconName = IconName.Gear,
    Text = "Test Level 2",
    IconColor = IconColor.Success,
    Match = NavLinkMatch.All,
    ParentId = "nav-test"
};

yield return new NavItem
{
    Id = "nav-test3",
    IconName = IconName.Gear,
    Text = "Test Level 3",
    IconColor = IconColor.Success,
    Match = NavLinkMatch.All,
    ParentId = "nav-test2"
};
```

You can do this unlimited times.

**Comment by MarvinKlein1508** [comment]
I've added another commit to change the demos.

**Comment by gvreddy04** [comment]
@MarvinKlein1508 I'll test all the scenarios.

**Comment by MarvinKlein1508** [comment]
@gvreddy04 just out of curiosity. Can you tell me what's the main purpose of the `SidebarDataProviderRequest`

For me it looks like it is just sorting the items and create nesting. Wouldn't it be much easier to simply define a `List<NavItem>` and pass this one to the component? 

It would less code to write since you don't need to rely on all the ids because you can simply add another NavItem as a child to another NavItem and so on.

**Pull request closed without merging**
